### ISSUE TITLE
Incompatible with any mods that use Highlander

### ISSUE THREAD

**Issue by Jesse-Culver** [bountygiver/WaveCOM-WOTC#7]
After narrowing down my mods to see what did and did not work with WaveCOM it appears anything that uses Highlander causes major issues. Adding just Highlander itself causes all menus in loadout to stop working as an example. Thanks for porting this over to WotC the work done so far is great!

**Comment by bountygiver** [comment]
this mod changes a lot of core features, it is never intended to be compatible with highlander

**Comment by Jesse-Culver** [comment]
Could that information be added to the readme then to clear up any
confusion?
